export const GETCOURSESSTARTED = "COURSES/GETCOURSESSTARTED";
export const GETCOURSESSUCCESS = "COURSES/GETCOURSESSUCCESS";
export const GETCOURSESFAILED = "COURSES/GETCOURSESFAILED";

export const SETCURRENTPAGE = "COURSES/SETCURRENTPAGE";

export const EDITCOURSESSTARTED = "COURSES/EDITCOURSESSTARTED";
export const EDITCOURSESSUCCESS = "COURSES/EDITCOURSESSUCCESS";
export const EDITCOURSESFAILED = "COURSES/EDITCOURSESFAILED";

export const SUBCOURSESSTARTED = "COURSES/SUBCOURSESSTARTED";
export const SUBCOURSESSUCCESS = "COURSES/SUBCOURSESSUCCESS";
export const SUBCOURSESFAILED = "COURSES/SUBCOURSESFAILED";

