export const GETCOURSESSTARTED = "COURSES/GETCOURSESSTARTED";
export const GETCOURSESSUCCESS = "COURSES/GETCOURSESSUCCESS";
export const GETCOURSESFAILED = "COURSES/GETCOURSESFAILED";

export const SETCURRENTPAGE = "COURSES/SETCURRENTPAGE";

export const EDITCOURSESSTARTED = "COURSES/EDITCOURSESSTARTED";
export const EDITCOURSESSUCCESS = "COURSES/EDITCOURSESSUCCESS";
export const EDITCOURSESFAILED = "COURSES/EDITCOURSESFAILED";

export const ADDCOURSESSTARTED = "COURSES/ADDCOURSESSTARTED";
export const ADDCOURSESSUCCESS = "COURSES/ADDCOURSESSUCCESS";
export const ADDCOURSESFAILED = "COURSES/ADDCOURSESFAILED";

