export const GETCOURSES_STARTED = "COURSES/GETCOURSES_STARTED";
export const GETCOURSES_SUCCESS = "COURSES/GETCOURSES_SUCCESS";
export const GETCOURSES_FAILED = "COURSES/GETCOURSES_FAILED";

export const SET_CURRENT_PAGE = "COURSES/SET_CURRENT_PAGE";

export const EDITCOURSES_STARTED = "COURSES/EDITCOURSES_STARTED";
export const EDITCOURSES_SUCCESS = "COURSES/EDITCOURSES_SUCCESS";
export const EDITCOURSES_FAILED = "COURSES/EDITCOURSES_FAILED";

