export const GETSTUDENT_STARTED = "student/GETSTUDENT_STARTED";
export const GETSTUDENT_SUCCESS = "student/GETSTUDENT_SUCCESS";
export const GETSTUDENT_FAILED = "student/GETSTUDENT_FAILED";

export const SET_CURRENT_PAGE = "student/SET_CURRENT_PAGE";

export const EDITSTUDENT_STARTED = "student/EDITSTUDENT_STARTED";
export const EDITSTUDENT_SUCCESS = "student/EDITSTUDENT_SUCCESS";
export const EDITSTUDENT_FAILED = "student/EDITSTUDENT_FAILED";

